name: Publish to Maven Central
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-natives:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: Linux
            arch: x86_64
          - os: macos-latest
            platform: Mac
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install CMake (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install CMake (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake

      - name: Build Native Library (Linux x86_64)
        if: runner.os == 'Linux' && matrix.arch == 'x86_64'
        run: |
          mkdir -p build
          cd build
          cmake ../src/main/cpp \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLAMA_STATIC=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DLLAMA_BUILD_EXAMPLES=OFF \
            -DLLAMA_BUILD_TESTS=OFF \
            -DLLAMA_METAL=OFF \
            -DLLAMA_NATIVE=OFF
          cmake --build . --config Release --verbose

      - name: Build Native Library (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p build
          cd build
          cmake ../src/main/cpp \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLAMA_STATIC=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DLLAMA_BUILD_EXAMPLES=OFF \
            -DLLAMA_BUILD_TESTS=OFF \
            -DLLAMA_METAL=ON \
            -DLLAMA_NATIVE=OFF \
            -DCMAKE_OSX_ARCHITECTURES=arm64
          cmake --build . --config Release --verbose

      - name: Generate Checksums
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            find build -type f -name "*.so" -exec sha256sum {} \; > checksums.txt
          else
            find build -type f -name "*.dylib" -exec shasum -a 256 {} \; > checksums.txt
          fi
        shell: bash

      - name: Upload Native Library
        uses: actions/upload-artifact@v3
        with:
          name: native-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            build/**/*.so
            build/**/*.dylib
            src/main/resources/ggml-metal.metal
            checksums.txt

  publish:
    needs: build-natives
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download All Native Libraries
        uses: actions/download-artifact@v3
        with:
          path: native-libs

      - name: Verify Checksums
        run: |
          for dir in native-libs/native-*; do
            if [ -f "$dir/checksums.txt" ]; then
              cd "$dir"
              if [ -f "*.so" ]; then
                sha256sum -c checksums.txt
              elif [ -f "*.dylib" ]; then
                shasum -a 256 -c checksums.txt
              fi
              cd ../..
            fi
          done
        shell: bash

      - name: Set up Java for publishing to Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
          server-id: maven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Organize Native Libraries
        run: |
          # Create resource directories
          mkdir -p src/main/resources/io/github/innobridge/llama/client/Linux/x86_64
          mkdir -p src/main/resources/io/github/innobridge/llama/client/Mac/aarch64

          # Copy Linux x86_64 libraries
          cp native-libs/native-Linux-x86_64/build/lib/*.so src/main/resources/io/github/innobridge/llama/client/Linux/x86_64/

          # Copy macOS ARM64 libraries
          cp native-libs/native-Mac-aarch64/build/lib/*.dylib src/main/resources/io/github/innobridge/llama/client/Mac/aarch64/
          cp src/main/resources/ggml-metal.metal src/main/resources/io/github/innobridge/llama/client/Mac/aarch64/

      - name: Publish to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            -P release \
            clean deploy
